name: 'Tickgit Action'
description: 'GitHub Action for running tickgit'
author: 'Andrew Mason <andrewmcodes@protonmail.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
env:
  GITHUB_TOKEN: secrets.GITHUB_TOKEN
branding:
  icon: 'shield'
  color: 'gray-dark'
